# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Vehicle.create(man_year: 1994, make: 'Subaru', model: 'Legacy', sub_model: 'L', engine: '2.2L 2212 CC H4', notes: '5 Door Station Wagon (AWD)')
Vehicle.create(man_year: 1981, make: 'Ford', model: 'F-150', sub_model: 'Custom', engine: '4.9L 300 CID L6 ', notes: '1/2 Ton Pickup (2WD - rear wheel drive)')
Vehicle.create(man_year: 2003, make: 'GMC', model: 'Yukon', sub_model: 'Denali XL', engine: '6.0L V-8', notes: 'AWD')

Term.create(name: 'Due on Receipt')
Term.create(name: 'Net 15')
Term.create(name: 'Net 30')
Term.create(name: 'Net 45')
Term.create(name: 'Net 60')
Term.create(name: 'Net 90')

AccessLevel.create(name: 'admin', description: 'Administrator Privileges')
AccessLevel.create(name: 'guest', description: 'Limited Privileges')
AccessLevel.create(name: 'client', description: 'Client Privileges')

BidStatus.create(name: 'waiting')
BidStatus.create(name: 'approved')
BidStatus.create(name: 'denied')
BidStatus.create(name: 'expired')

ExpenseCategory.create(name: 'Assets (Depreciation)', description: 'Tools or Equipment over $100 (include tax and shipping)')
ExpenseCategory.create(name: 'Vehicle Gas', description: 'Gasoline for Vehicle')
ExpenseCategory.create(name: 'Vehicle Tires', description: 'Tires for Vehicle')
ExpenseCategory.create(name: 'Vehicle Repair', description: 'Brakes, Engine, Transmission, etc')
ExpenseCategory.create(name: 'Vehicle Maintenance', description: 'Oil change, Oil/Air Filter, Light Bulbs, etc')
ExpenseCategory.create(name: 'Supplies', description: 'Small Tools, Drill Bits, Screws, Hoses, Cords, Nails, Safety Equipment, Protective Clothes, etc')
ExpenseCategory.create(name: 'Materials', description: 'Lumber, Hardware, etc')
ExpenseCategory.create(name: 'Communication', description: 'Second Phone Line, Long Distance, Cell Phone Service')
ExpenseCategory.create(name: 'Home Office', description: 'Mortgage Interest, Rent, Utilities, Homeowner/Renters Insurance')
ExpenseCategory.create(name: 'Taxes and Licenses', description: 'Payroll, Business Licenses, Permits')
ExpenseCategory.create(name: 'Advertising', description: 'Business Cards, PhoneBook Ads, Web Ads, Flyers, Brochures')
ExpenseCategory.create(name: 'Business Travel', description: 'Air Fare, Hotel, Rental Car')
ExpenseCategory.create(name: 'Insurance Payments', description: 'Liability Insurance')
ExpenseCategory.create(name: 'Rental Payments', description: 'Equipment such as computers, tools, warehouse space or land')
ExpenseCategory.create(name: 'Legal and Professional Fees', description: 'Fees for business-related legal matters')
ExpenseCategory.create(name: 'Commissions', description: 'Finder\'s Fees, Sales Commissions, Legal Referrals')
ExpenseCategory.create(name: 'Contract Labor', description: 'Sub- and independent Contractors, Additional Project Support')
ExpenseCategory.create(name: 'Repairs and Maintenance', description: 'Painting, Plumbing, Electrical, Computer Services')
ExpenseCategory.create(name: 'Utilities (for Business, not Personal)', description: 'Gas, Electricity, Water, Trash, Alarm Monitoring')
ExpenseCategory.create(name: 'Other Office Expenses', description: 'Pickup and Delivery Services, Data Backup')
ExpenseCategory.create(name: 'Miscellaneous Expenses', description: 'Answering Services, Bank Charges, Business-related Gifts')
ExpenseCategory.create(name: 'Equipment Gas', description: 'Gasoline for Equipment')
ExpenseCategory.create(name: 'Vehicle Oil', description: 'Oil for Vehicle')
ExpenseCategory.create(name: 'Waste Disposal', description: 'Waste Disposal')
ExpenseCategory.create(name: 'Vehicle Insurance', description: 'Auto Insurance')
ExpenseCategory.create(name: 'Vehicle Registration/License', description: 'Registration/Licensing Fees')
ExpenseCategory.create(name: 'Vehicle - Garage Rent', description: 'Garage Rent')
ExpenseCategory.create(name: 'Vehicle - Other Expense', description: 'Towing, Tools for Vehicle, Car Wash')
ExpenseCategory.create(name: 'Office Supplies', description: 'Memberships, Books, Pencils, Paper')
